# Generated by Django 4.2.3 on 2023-08-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_comment_comment_commenttext_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
