# Generated by Django 4.2.3 on 2023-08-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='amount',
        ),
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
